source 'https://github.com/aliyun/aliyun-specs'
target 'YTKNetworkDemo' do
  pod 'YTKNetwork', :path => '../'
  pod 'AFNetworking', '~> 4.0'
  pod 'AlicloudHTTPDNS'
end

target 'YTKNetworkDemoTests' do
  pod 'YTKNetwork', :path => '../'
end
